import type { SimpleGit } from 'simple-git';
import type { FastifyBaseLogger } from 'fastify';
import { withRetry, GIT_PUSH_RETRY_OPTIONS } from './retry.js';

/**
 * Files generated by the Copilot workflow that should never be committed.
 * Matches the filter list used in the shell scripts.
 */
const INTERMEDIATE_FILE_PATTERNS = [
  'patch_raw.txt',
  'patch_clean.txt',
  'copilot.patch',
  'todo.md',
  'todo_completed.md',
  'plan.json',
  'plan.env',
  'commit_msg.txt',
  'commit_msg_raw.txt',
  'mr_summary.txt',
  'review_findings.json',
  'review_summary.txt',
  'review_summary_final.txt',
  'review_raw.txt',
  'review_clean.txt',
  'review_comment.txt',
  'mr.json',
  'mr.env',
  'mr_description.txt',
  'updated_description.txt',
  'existing_mr.json',
  'authed_repo_url.txt',
  'copilot_output.log',
  'full_diff.txt',
  '__pycache__',
];

const INTERMEDIATE_EXTENSIONS = ['.pyc'];

function isIntermediateFile(filename: string): boolean {
  if (INTERMEDIATE_FILE_PATTERNS.some((pattern) => filename.includes(pattern))) {
    return true;
  }
  if (INTERMEDIATE_EXTENSIONS.some((ext) => filename.endsWith(ext))) {
    return true;
  }
  return false;
}

/**
 * Stage files for commit, excluding intermediate/workflow files.
 * Replicates the shell script logic:
 *   1. Stage all tracked modifications (git add -u)
 *   2. Find untracked files, filter out intermediate ones, then add them
 */
export async function stageFilesSelectively(
  git: SimpleGit,
  logger?: FastifyBaseLogger,
): Promise<{ hasChanges: boolean; stagedFiles: string[] }> {
  // Stage tracked file modifications
  await git.add(['-u']);

  // Get untracked files (excluding standard ignores)
  const rawUntracked = await git.raw(['ls-files', '--others', '--exclude-standard']);
  const untrackedFiles = rawUntracked
    .split('\n')
    .map((f) => f.trim())
    .filter((f) => f.length > 0 && !isIntermediateFile(f));

  if (untrackedFiles.length > 0) {
    logger?.debug({ files: untrackedFiles }, 'Adding untracked files');
    await git.add(untrackedFiles);
  }

  // Check if anything is staged
  const diffStat = await git.diff(['--cached', '--stat']);
  const hasChanges = diffStat.trim().length > 0;

  return { hasChanges, stagedFiles: untrackedFiles };
}

/**
 * Push with retry logic matching shell scripts (3 attempts, 5s delay).
 */
export async function pushWithRetry(
  git: SimpleGit,
  branch: string,
  logger?: FastifyBaseLogger,
): Promise<void> {
  await withRetry(
    async () => {
      await git.push(['origin', branch]);
    },
    logger,
    GIT_PUSH_RETRY_OPTIONS,
  );
}
